---
# roles/wordpress/defaults/main.yml

# Liste des paquets à installer sur RHEL/CentOS
web_pkgs_redhat:
  - httpd       # serveur web Apache
  - php         # langage PHP
  - php-mysqlnd # extension PHP pour MariaDB/MySQL
  - mariadb     # client MariaDB (pour connexion CLI, libs)
  - unzip       # décompression d’archives ZIP
  - curl        # téléchargement de fichiers depuis URL

# Liste des paquets à installer sur Debian/Ubuntu
web_pkgs_debian:
  - apache2     # serveur web Apache
  - php         # langage PHP
  - php-mysql   # extension PHP pour MySQL
  - mysql-client# client MySQL (CLI)
  - unzip       # décompression d’archives ZIP
  - curl        # téléchargement de fichiers depuis URL

