- name: Installer le dépôt EPEL (RedHat/CentOS)
  yum:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Mettre à jour le cache yum
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Installer les paquets web (RedHat)
  yum:
    name:
      - httpd
      - php
      - php-mysqlnd
      - mariadb
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
