- name: Installer le dépôt EPEL (RedHat/CentOS)
  yum:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Mettre à jour le cache yum
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Installer les paquets web (RedHat)
  yum:
    name:
      - httpd
      - php
      - php-mysqlnd
      - mariadb
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

# - name: Copier les fichiers web vers le serveur WordPress
#   ansible.builtin.copy:
#     src: ../ansible/web/
#     dest: /var/www/html/wordpress/
#     owner: apache
#     group: apache
#     mode: '0644'
#     recurse: yes

- name: Copier le dossier web entier avec synchronize
  ansible.builtin.synchronize:
    src: ansible/web/
    dest: /var/www/html/wordpress/
    recursive: yes
    delete: yes
  delegate_to: localhost

- name: Changer les permissions des fichiers web
  ansible.builtin.file:
    path: /var/www/html/wordpress/
    recurse: yes
    owner: apache
    group: apache



