- name: Installer les paquets nécessaires
  yum:
    name:
      - httpd
      - php
      - php-mysqlnd
      - mariadb
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Démarrer et activer Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip

- name: Décompresser WordPress
  unarchive:
    src: /tmp/wordpress.zip
    dest: /var/www/html/
    remote_src: yes

- name: Définir les permissions
  file:
    path: /var/www/html/wordpress
    state: directory
    recurse: yes
    owner: apache
    group: apache
    mode: "0755"
