
---
# roles/wordpress/defaults/main.yml

# Paquets pour RHEL/CentOS
web_pkgs_redhat:
  - httpd
  - php
  - php-mysqlnd
  - mariadb
  - unzip
  - curl

# Paquets pour Debian/Ubuntu
web_pkgs_debian:
  - apache2
  - php
  - php-mysql
  - mysql-client
  - unzip
  - curl
