- name: Installer MariaDB Server et configurer la base (Red Hat)
  hosts: mysql
  become: yes
  tasks:
    - name: Installer MariaDB Server
      yum:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Démarrer et activer le service MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Installer PyMySQL pour Python 3
      package:
        name: python3-PyMySQL
        state: present

    - name: Créer base de données WordPress
      mysql_db:
        name: wordpress
        state: present
