- name: Installer SonarQube sur les VMs WordPress
  hosts: wordpress
  become: true
  tasks:

    - name: Installer le dépôt EPEL (nécessaire pour certains paquets)
      yum:
        name: epel-release
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Installer Java (prérequis pour SonarQube)
      yum:
        name: java-17-openjdk-devel
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Créer l'utilisateur sonarqube
      user:
        name: sonarqube
        shell: /bin/bash
        create_home: yes

    - name: Installer unzip s'il n'est pas là
      yum:
        name: unzip
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Télécharger SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.1.88267.zip
        dest: /tmp/sonarqube.zip

    - name: Décompresser SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt/
        remote_src: yes

    - name: Trouver le dossier SonarQube extrait
      find:
        paths: /opt/
        patterns: "sonarqube-*"
        file_type: directory
      register: sonarqube_dirs

    - name: Supprimer le lien /opt/sonarqube s'il existe
      file:
        path: /opt/sonarqube
        state: absent
        force: yes

    - name: Créer un lien symbolique /opt/sonarqube vers le dossier extrait
      file:
        src: "{{ sonarqube_dirs.files[0].path }}"
        dest: /opt/sonarqube
        state: link

    - name: Changer le propriétaire
      file:
        path: /opt/sonarqube
        state: directory
        recurse: yes
        owner: sonarqube
        group: sonarqube

    - name: Créer le service systemd pour SonarQube
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=syslog.target network.target

          [Service]
          Type=forking

          ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

          User=sonarqube
          Group=sonarqube
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Recharger systemd
      command: systemctl daemon-reexec

    - name: Activer et démarrer SonarQube
      systemd:
        name: sonarqube
        enabled: yes
        state: started
