- name: Installer NGINX
  yum:
    name: nginx
    state: present
    update_cache: yes

- name: Configurer NGINX en reverse proxy
  template:
    src: lb.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Redémarrer NGINX
  service:
    name: nginx
    state: restarted
